import Head from "next/head";

export default async function ServerDemo() {
    const res = await fetch("https://www.timeapi.io/api/Time/current/zone?timeZone=America/New_York", { cache: 'no-store' });
    const data = await res.json();
    return (
        <>
            <Head>
                <title>Next Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main>
                <h1 style={{ flex: 1 }}>{new Date(data.dateTime).toTimeString()}</h1>
            </main>
        </>
    )
}