import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Next Demo</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>

        <div className={styles.center}>
          <div className={styles.grid}>
            <a
              href="/csr"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Client Side Rendering <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Typical react rendering that occurs on the client side.
              </p>
            </a>

            <a
              href="/ssr"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Server Side Rendering <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Rending on the server to boost SEO.
              </p>
            </a>

            <a
              href="/isr"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Incremental Site Regeneration <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Rendering on the server with timeout to add speed and SEO.
              </p>
            </a>

            <a
              href="/ssg"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                Static Site Generation <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Rendering at build time to provide super fast renders.
              </p>
            </a>

            <a
              href="/serve"
              className={styles.card}
              target="_blank"
              rel="noopener noreferrer"
            >
              <h2 className={inter.className}>
                React Server Components <span>-&gt;</span>
              </h2>
              <p className={inter.className}>
                Working entirely on the server to combine SSR and SSG.
              </p>
            </a>
          </div>
        </div>
      </main>
    </>
  )
}
