import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useRouter } from 'next/router'
import { useState } from 'react'


export default function CSR() {
    const router = useRouter()
    const { msg } = router.query

    const [counter, setCounter] = useState(0)

    return (
        <>
            <Head>
                <title>Next Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 style={{ flex: 1 }}>{msg}</h1>
                <div style={{ flex: 4 }}>
                    <h1>Counter: {counter}</h1>
                    <button style={{ padding: 5, marginTop: 5 }} onClick={() => setCounter(counter + 1)}>Click me</button>
                </div>
            </main>
        </>
    )
}
