import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'


export default function CSR() {
    const [title, setTitle] = useState("Loading...")
    const [text, setText] = useState("Loading...")

    useEffect(() => {
        (async () => {
            const res = await fetch('https://dummyjson.com/products/1')
            const data = await res.json();
            setTitle(data.title)
            setText(data.description)
        })()
    }, [])

    return (
        <>
            <Head>
                <title>Next Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 style={{ flex: 1 }}>{title}</h1>
                <h2 style={{ flex: 4 }}>{text}</h2>
            </main>
        </>
    )
}
