import Head from 'next/head'
import styles from '@/styles/Home.module.css'
import { useEffect, useState } from 'react'


export default function CSR() {
    const [time, setTime] = useState("Loading...")

    useEffect(() => {
        (async () => {
            const res = await fetch("https://worldtimeapi.org/api/ip");
            const data = await res.json();
            setTime(data.datetime)
        })()
    }, [])

    return (
        <>
            <Head>
                <title>Next Demo</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <main className={styles.main}>
                <h1 style={{ flex: 1 }}>{time}</h1>
            </main>
        </>
    )
}
